version: 2
jobs:
  build:
    working_directory: ~/demo
    docker:
      - image: circleci/node:9-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: build
          command: yarn run build
      - run:
          name: test
          command: yarn run test-coverage
      - run:
          name: codacy
          command: yarn run codacy
      - store_artifacts:
          path: coverage
          prefix: coverage
