// src/constants/index.tsx

export const REQUEST_POSTS = 'REQUEST_POSTS';
export type REQUEST_POSTS = typeof REQUEST_POSTS;

export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export type RECEIVE_POSTS = typeof RECEIVE_POSTS;

export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
export type SELECT_SUBREDDIT = typeof SELECT_SUBREDDIT;

export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';
export type INVALIDATE_SUBREDDIT = typeof INVALIDATE_SUBREDDIT;
